#!/usr/bin/env bash
# Uses while loop to read /etc/passwd and uses the fields
#  to make a story

IFS=":"
while read -r -a data
do
	echo "The user ${data[0]} is part of the ${data[3]} gang,"\
	"lives in ${data[5]} and rides ${data[6]}. ${data[2]}'s place is"\
	"protected by the passcode ${data[1]}, more info about the user"\
	"here: ${data[4]}"
done < /etc/passwd
