#!/usr/bin/env bash
# Uses while loop to display Best School 10 times displaying Hi
#  after the ninth iteration
i=1
while (( i<=10 ))
do
	echo 'Best School'
	if (( i==9 ))
	then
		echo 'Hi'
	fi
	i=$(( i+1 ))
done
