#!/usr/bin/env bash
# Running Nginx as Nginx
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sudo sed -i -r "s/(listen \[*:*]*:*)80/\18080/g" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
